### ISSUE TITLE
DSQL - Feature Check!

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#874]
We must have the following features, all documented, tested and coded.
- [x] get()
- [x] raw query
- [ ] execute multiple statements
- [x] where
- [ ] count(), exists()
- [ ] min,max()
- [ ] sum,avg()
- [x] distinct atk4/dsql#62 
- [x] calc found rows atk4/dsql#62 
- [x] raw expressions 
- [x] join
- [ ] union
- [ ] union all
- [x] or
- [ ] between
- [x] where in 
- [x] where null
- [ ] where ( .. or .. ) and ..
- [ ] where exists ( select .. from .. )
- [x] having 
- [ ] having raw 
- [ ] insert one
- [ ] insert multiple
- [x] insert delayed atk4/dsql#62 
- [ ] insert on duplicate key
- [ ] get id of inserted record 
- [ ] replace 
- [ ] update where
- [ ] increment / decrement
- [ ] delete
- [ ] truncate
- [ ] lock 
- [ ] transaction
- [ ] atomic
- [ ] get query
- [ ] get bindings
- [ ] get pdo
- [ ] support mysqli (wordpress, and some other libs are stuck with it)
- [ ] change fetch mode
- [x] "case" support atk4/dsql#74

**Comment by mvorisek** [comment]
impl. once some feature is needed
